---
prometheus_version: "2.53.4"
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_storage_retention: "7d"
prometheus_storage_retention_size: "1GB"
prometheus_firewall_enabled: false  # Disable for testing

# Basic scrape configs for testing
prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    
  - job_name: 'node-test'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

# Test alert rules
prometheus_alert_rules:
  - name: test_alerts
    rules:
      - alert: TestInstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          environment: test
        annotations:
          summary: "Test instance {{ $labels.instance }} is down"
          description: "Instance has been down for more than 1 minute"