# =============================================================================
# molecule/default/prepare.yml - Enhanced container preparation for two-node setup
# =============================================================================

---
- name: Prepare all containers
  hosts: all
  become: true
  gather_facts: true
  tasks:
    # https://github.com/geerlingguy/docker-fedora41-ansible/issues/2#issuecomment-2808050083
    # This is a problem that appears unique to Github Actions
    - name: TEMP | Fix due to PAM error in some upstream images
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'Rocky'
      # Explicitly don't try to become because that will trigger the broken PAM error
      # become: true
      # Bug in some upstream distros, /etc/shadow has no file perms in container image
      ansible.builtin.file:
        path: /etc/shadow
        mode: '400'

    - name: Update package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Update package cache (RedHat/CentOS)
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Install base system dependencies
      ansible.builtin.package:
        name:
          - tar
          - gzip
          - unzip
          - python3
          - python3-pip
        state: present

    - name: Install network utilities for testing
      ansible.builtin.package:
        name:
          - net-tools
        state: present
      when: ansible_os_family == "Debian"

    - name: Install network utilities for testing (RedHat)
      ansible.builtin.package:
        name:
          - net-tools
        state: present
      when: ansible_os_family == "RedHat"

- name: Prepare monitoring server
  hosts: monitoring_server
  become: true
  tasks:
    - name: Install monitoring server specific packages
      ansible.builtin.package:
        name:
          - fontconfig
          - libfontconfig1
        state: present
      when: ansible_os_family == "Debian"

    - name: Create required directories for Grafana
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/lib/grafana
        - /var/log/grafana
        - /etc/grafana
