---
# =============================================================================
# Main verify.yml - Clean orchestration of verification tasks
# =============================================================================

- name: Verify monitoring server components
  hosts: monitoring_server
  become: true
  tasks:
    - name: Verify Prometheus service and API
      import_tasks: verify/prometheus-check.yml

    - name: Verify AlertManager service and API
      import_tasks: verify/alertmanager-check.yml

    - name: Verify Grafana service and health
      import_tasks: verify/grafana-check.yml

    - name: Verify Node Exporter on monitoring server
      import_tasks: verify/node-exporter-check.yml

- name: Verify database server components  
  hosts: database_server
  become: true
  tasks:
    - name: Verify PostgreSQL service and connectivity
      import_tasks: verify/postgres-check.yml

    - name: Verify postgres_exporter functionality
      import_tasks: verify/postgres-exporter-check.yml

    - name: Verify Node Exporter on database server
      import_tasks: verify/node-exporter-check.yml

- name: Verify cross-server monitoring integration
  hosts: monitoring_server
  become: true
  tasks:
    - name: Test remote connectivity and metrics collection
      import_tasks: verify/integration-check.yml

    - name: Display monitoring stack summary
      import_tasks: verify/summary-display.yml