# =============================================================================
# molecule/default/converge.yml - Role execution
# =============================================================================

---
- name: Converge
  hosts: all
  become: true
  roles: 
    - prometheus