# =============================================================================
# molecule/default/converge.yml - Role execution
# =============================================================================

---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include prometheus role
      include_role:
        name: prometheus
      vars:
        prometheus_config_flags_extra:
          log.level: info
          web.enable-lifecycle: true

    - name: Wait for Prometheus to be ready
      wait_for:
        port: 9090
        host: "0.0.0.0"
        delay: 10
        timeout: 120
      register: prometheus_ready

    - name: Debug Prometheus startup
      debug:
        msg: "Prometheus should be ready on port 9090"
      when: prometheus_ready is succeeded