---
scenario:
  name: prometheus

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: prometheus-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - prometheus_servers
    published_ports:
      - "9090:9090"

  - name: prometheus-rockylinux8
    image: geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/usr/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - prometheus_servers
    published_ports:
      - "9091:9090"

  - name: prometheus-debian11
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - prometheus_servers
    published_ports:
      - "9092:9090"

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../roles  # Point to the roles directory
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
      result_format: yaml
  env:
    ANSIBLE_ROLES_PATH: ../../roles  # Additional environment variable
verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint