# =============================================================================
# molecule/default/prepare.yml - Container preparation
# =============================================================================

---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install Python for Ansible
      raw: |
        if [ -f /usr/bin/apt-get ]; then
          apt-get update && apt-get install -y python3 python3-pip curl
        elif [ -f /usr/bin/yum ]; then
          yum makecache && yum install -y python3 python3-pip curl
        elif [ -f /usr/bin/dnf ]; then
          dnf makecache && dnf install -y python3 python3-pip curl
        fi
      changed_when: false

    - name: Gather facts
      setup:

    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Update package cache (RedHat/CentOS)
      yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Install additional test dependencies
      package:
        name:
          - curl
          - wget
          - tar
          - gzip
        state: present