# =============================================================================
# molecule/default/prepare.yml - Container preparation
# =============================================================================

---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Gather facts
      setup:

    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Update package cache (RedHat/CentOS)
      yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Install additional test dependencies
      package:
        name:
          - curl
          - wget
          - tar
          - gzip
        state: present