# =============================================================================
# tasks/configure.yml - Configuration management
# =============================================================================

---
- name: Generate prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_file }}"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: '0644'
    backup: true
  become: true
  notify:
    - reload prometheus
  tags:
    - prometheus
    - configuration

- name: Validate prometheus configuration
  command: >
    {{ prometheus_binary_install_dir }}/promtool check config {{ prometheus_config_file }}
  become: true
  become_user: "{{ prometheus_system_user }}"
  register: prometheus_config_check
  changed_when: false
  failed_when: 
    - prometheus_config_check.rc != 0
    - "'FAILED' in prometheus_config_check.stderr"
  tags:
    - prometheus
    - configuration

- name: Generate web configuration
  template:
    src: web-config.yml.j2
    dest: "{{ prometheus_web_config_file }}"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: '0644'
    backup: true
  become: true
  when: prometheus_web_config | length > 0
  notify:
    - reload prometheus
  tags:
    - prometheus
    - configuration

- name: Copy alert rules files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: '0644'
  become: true
  loop:
    - "{{ prometheus_alert_rules_files }}"
  when: prometheus_alert_rules_files | length > 0
  notify:
    - reload prometheus
  tags:
    - prometheus
    - configuration

- name: Generate file service discovery targets
  copy:
    content: "{{ prometheus_targets[item] | to_nice_yaml }}"
    dest: "{{ prometheus_config_dir }}/file_sd/{{ item }}.yml"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: '0644'
  become: true
  loop: "{{ prometheus_targets.keys() | list }}"
  when: prometheus_targets | length > 0
  notify:
    - reload prometheus
  tags:
    - prometheus
    - configuration