# =============================================================================
# tasks/install.yml - Installation tasks
# =============================================================================

---
- name: Install system packages
  package:
    name: "{{ prometheus_system_packages }}"
    state: present
  become: true
  tags:
    - prometheus
    - installation

- name: Create prometheus system group
  group:
    name: "{{ prometheus_system_group }}"
    system: true
    state: present
  become: true
  tags:
    - prometheus
    - installation

- name: Create prometheus system user
  user:
    name: "{{ prometheus_system_user }}"
    system: true
    shell: "{{ prometheus_shell }}"
    group: "{{ prometheus_system_group }}"
    createhome: "{{ prometheus_create_home }}"
    home: "{{ prometheus_data_dir }}"
    state: present
  become: true
  tags:
    - prometheus
    - installation

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: '0755'
  become: true
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_log_dir }}"
    - "{{ prometheus_runtime_dir }}"
  tags:
    - prometheus
    - installation

- name: Download prometheus archive checksum
  get_url:
    url: "{{ prometheus_checksums_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}-checksums.txt"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false
  tags:
    - prometheus
    - installation

- name: Extract expected checksum
  shell: |
    grep "{{ prometheus_archive }}" "/tmp/prometheus-{{ prometheus_version }}-checksums.txt" | awk '{print $1}'
  register: prometheus_expected_checksum
  delegate_to: localhost
  run_once: true
  become: false
  changed_when: false
  tags:
    - prometheus
    - installation

- name: Download prometheus binary archive
  get_url:
    url: "{{ prometheus_binary_url }}"
    dest: "{{ prometheus_archive_path }}"
    checksum: "sha256:{{ prometheus_expected_checksum.stdout }}"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false
  tags:
    - prometheus
    - installation

- name: Extract prometheus archive
  unarchive:
    src: "{{ prometheus_archive_path }}"
    dest: /tmp
    remote_src: false
    owner: root
    group: root
    mode: '0755'
  become: true
  tags:
    - prometheus
    - installation

- name: Install prometheus binaries
  copy:
    src: "{{ prometheus_binary_local_dir }}/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  become: true
  loop: "{{ prometheus_binaries }}"
  notify:
    - restart prometheus
  tags:
    - prometheus
    - installation

- name: Install prometheus console files
  copy:
    src: "{{ prometheus_binary_local_dir }}/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: '0644'
    remote_src: true
  become: true
  loop: "{{ prometheus_console_files }}"
  tags:
    - prometheus
    - installation

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ prometheus_archive_path }}"
    - "{{ prometheus_binary_local_dir }}"
    - "/tmp/prometheus-{{ prometheus_version }}-checksums.txt"
  delegate_to: localhost
  run_once: true
  become: false
  tags:
    - prometheus
    - installation