# =============================================================================
# tasks/preflight.yml - Pre-installation validation
# =============================================================================

---
- name: Assert supported platform
  assert:
    that:
      - ansible_os_family in ['RedHat', 'Debian']
      - ansible_architecture in ['x86_64', 'aarch64', 'armv7l']
    fail_msg: "Prometheus role only supports RedHat/Debian family on x86_64/aarch64/armv7l architectures"
    success_msg: "Platform {{ ansible_os_family }}/{{ ansible_architecture }} is supported"
  tags:
    - prometheus
    - preflight

- name: Check if running in privileged mode
  command: id -u
  register: current_user_id
  changed_when: false
  failed_when: current_user_id.stdout != "0" and not ansible_check_mode
  tags:
    - prometheus
    - preflight

- name: Validate Prometheus version format
  assert:
    that:
      - prometheus_version is regex('^[0-9]+\.[0-9]+\.[0-9]+$')
    fail_msg: "prometheus_version must be in format X.Y.Z (semantic versioning)"
    success_msg: "Prometheus version {{ prometheus_version }} format is valid"
  tags:
    - prometheus
    - preflight

- name: Validate retention settings
  assert:
    that:
      - prometheus_storage_retention is regex('^[0-9]+[smhdwy]$')
      - prometheus_storage_retention_size is regex('^[0-9]+[KMGTPE]?B$')
    fail_msg: "Invalid retention format. Use time units (s,m,h,d,w,y) and size units (KB,MB,GB,TB,PB,EB)"
    success_msg: "Retention settings are valid"
  tags:
    - prometheus
    - preflight

- name: Check available disk space
  setup:
    gather_subset: 
      - hardware
  tags:
    - prometheus
    - preflight

- name: Ensure sufficient disk space
  assert:
    that:
      - ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='size_available') | first > 5368709120  # 5GB
    fail_msg: "Insufficient disk space. Prometheus requires at least 5GB free space"
    success_msg: "Sufficient disk space available"
  tags:
    - prometheus
    - preflight