---
- name: Check node exporter service
  ansible.builtin.systemd:
    name: node_exporter
  register: node_exporter_service

- name: Verify node exporter is running
  ansible.builtin.assert:
    that:
      - node_exporter_service.status.ActiveState == "active"
      - node_exporter_service.status.SubState == "running"
    fail_msg: "Node exporter service is not running on {{ inventory_hostname }}"
    success_msg: "Node exporter service is running on {{ inventory_hostname }}"

- name: Test node exporter metrics
  ansible.builtin.uri:
    url: "http://localhost:9100/metrics"
    method: GET
    return_content: true
  register: node_metrics

- name: Verify node exporter metrics
  ansible.builtin.assert:
    that:
      - node_metrics.status == 200
      - "'node_cpu_seconds_total' in node_metrics.content"
      - "'node_memory_MemTotal_bytes' in node_metrics.content"
    fail_msg: "Node exporter metrics not available on {{ inventory_hostname }}"
    success_msg: "Node exporter metrics are available on {{ inventory_hostname }}"