# =============================================================================
# defaults/main.yml - Default variables for Prometheus role
# =============================================================================

---
# Prometheus version and installation
prometheus_version: "2.53.4"
prometheus_platform_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ prometheus_platform_architecture }}.tar.gz"
prometheus_checksums_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/sha256sums.txt"

# System user and directories
prometheus_system_user: prometheus
prometheus_system_group: prometheus
prometheus_shell: /sbin/nologin
prometheus_create_home: false

# Installation directories
prometheus_binary_install_dir: /usr/local/bin
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_log_dir: /var/log/prometheus
prometheus_runtime_dir: /run/prometheus

# Configuration paths
prometheus_config_file: "{{ prometheus_config_dir }}/prometheus.yml"
prometheus_web_config_file: "{{ prometheus_config_dir }}/web-config.yml"
prometheus_pid_file: "{{ prometheus_runtime_dir }}/prometheus.pid"

# Network configuration
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ""
prometheus_web_route_prefix: "/"
prometheus_web_telemetry_path: "/metrics"

# Storage configuration
prometheus_storage_retention: "30d"
prometheus_storage_retention_size: "10GB"
prometheus_storage_tsdb_path: "{{ prometheus_data_dir }}"
prometheus_storage_tsdb_wal_compression: true

# Global configuration
prometheus_global_config:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels: {}

# Remote storage (optional)
prometheus_remote_write: []
prometheus_remote_read: []

# Rule configuration
prometheus_rule_files:
  - "{{ prometheus_config_dir }}/rules/*.yml"
prometheus_alert_rules: []
prometheus_alert_rules_files: []
prometheus_recording_rules: []

# Alertmanager configuration
prometheus_alertmanager_config: []

# Scrape configurations
prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    scrape_timeout: 5s

# File service discovery
prometheus_targets: {}

# Security configuration
prometheus_web_config:
  tls_server_config: {}
  http_server_config: {}
  basic_auth_users: {}

# Service configuration
prometheus_systemd_service_enabled: true
prometheus_systemd_service_state: started
prometheus_systemd_restart_policy: "on-failure"
prometheus_systemd_restart_sec: 5

# Additional command line flags
prometheus_config_flags_extra: {}

# Resource limits
prometheus_limit_nofile: 65536
prometheus_limit_memlock: infinity

# Firewall configuration
prometheus_firewall_enabled: false
prometheus_firewall_zone: public